### ISSUE TITLE
Missing hotbar spells upon creation

### ISSUE THREAD

**Issue by heyitsbench** [heyitsbench/mod-worgoblin#27]
Worgen (and probably goblins too) don't have any spells in their hotbar when they are created. Probably playercreatinfo_action, but idk.

**Comment by benjymansy123** [comment]
Basic spells added here: https://github.com/benjymansy123/mod-worgoblin/commit/87f804bd23d829b481bc52f042544e24985b04bf, but other spells will need to be added later, such as darkflight.

**Comment by benjymansy123** [comment]
Given that my eventual goal (Maybe not for the module on its own, but at least my own server) is not to have the worgen racials available from creation, I feel it fitting to have the racial spells inside the query already for those that want them, but commented out. And also given that Blizzard themselves were inconsistent on where they wanted racial spells to be, I didn't put them in actual places, so not only would you have to fix the comments, but also choose an actual location for them to be in a given bar. If anyone disagrees with this method of handling, I'd love to hear your reasoning, but until then I'm gonna say this issue is closed.

**Comment by benjymansy123** [comment]
I've discovered goblins are still not getting spells in their hotbar after those commits, so I'm reopening this. Probably needs some DBC work.

**Comment by benjymansy123** [comment]
Apparently I was testing with a bad DB, it did work. Closing again.

**Comment by heyitsbench** [comment]
If TCPP is to be trusted, Goblins are supposed to have rocket jump/rocket barrage on the hotbar, rocket jump on 0, rocket barrage on -, at least on a warrior. I'll do that.

**Comment by heyitsbench** [comment]
So Rocket Jump on 0 and Rocket Barrage on - apply to all Goblin characters, not just warrior. Pack Hobgoblin is on = for death knights as well, also Gobber is summoned in front of the Goblin, so that's gotta get fixed too eventually.

**Comment by heyitsbench** [comment]
And on that note, Worgen death knights get darkflight on 0, two forms on -, and running wild on =.

**Comment by heyitsbench** [comment]
Okay, with the addition of Rocket Barrage and adding it to the hotbar in https://github.com/heyitsbench/mod-worgoblin/commit/a0aea9aab1cdb9d571c50ea948aee97d7d518035, this issue is closed permanently in my eyes. Maybe I'll change the commented Worgen racials to match their blizzlike positions, but I don't care about that right now so 🤷‍♀️.
